# 注释
[server]
# debug 开发模式 release 生产模式
AppMode = debug
HttpPort = :3000
JwtKey = 25js47js10

[database]
Db = mysql
DbHost = localhost
DbPort = 3306
DbUser = ginblog
DbPassWord = admin123
DbName = ginblog

[qiniu]
AccessKey   = h7TJbWF0B6vm-xGmiUWfq8joyKDjA52CtgwF1a3B
SecretKey   = jj7viWPy01FRu0GPmJsZA9DtMmL2uK8YfPH612rQ
Bucket      = jwj2025ginblog
QiniuServer = http://suj81xvyk.hd-bkt.clouddn.com/